### get all countries
GET http://localhost:3001/countries HTTP/1.1
### get country by code
GET http://localhost:3001/countries?name=mex HTTP/1.1
### get pokemon by name
GET http://localhost:3001/countries/mex HTTP/1.1

### get pokemon by name
GET http://localhost:3001/activity HTTP/1.1
### create an activity
POST http://localhost:3001/activity HTTP/1.1
content-type: application/json

{
    "name": "surf",
    "difficulty": "3",
    "duration": "5",
    "season": "summer",
    "countries": ["ATF", "MEX", "ARG"]
}

### sudo service postgresql start
### sudo -u postgres psql